### ISSUE TITLE
add STSPIN32F0A and STSPIN32F0 support. 

### ISSUE THREAD

**Issue by bnn1044** [betaflight/betaflight-esc#33]
please add this two chip support also using stm32f0. I have the hardware almost ready for dev to test.

thanks.

**Comment by conuthead** [comment]
I have been playing with this chip, no comparators unfortunately, have to use the adc.

**Comment by bnn1044** [comment]
@conuthead  there are 3-4 opamps on it.

**Comment by conuthead** [comment]
Yes, I wonder what the better approach is? To use the op-amps or the adc. St has a 6 step library for the stspinf0 that just uses the ADC. Have you got your hardware?  I have a few dev boards with different configurations for the stspinf0 and stspinf0a.

**Comment by bnn1044** [comment]
Yeah I have the hardware working on the blheli_32BIT





Cheng Lin
Cell: 203-243-5683

**Comment by conuthead** [comment]
What have you tried so far? I am playing around with this right now, ran my bemf sense lines to the adc. Having trouble with getting clean adc readings, Working on more hardware filtering but i have got a back emf version running crudely..  
I just discovered this github project yesterday by accident, its there a forum where we can discuss hardware and the developing firmware? I had just finished writing a firmware compatible with wraith32 but using HAL library.

**Comment by brycedjohnson** [comment]
On the betaflightgroup.slack.com there is a #open_esc_firmware channel.  The invite server is down so someone would need to add you manually (I don't know if I can?).  I don't think anyone had a motor spinning in the betaflight-esc yet, but we would love to collaborate! 

Currently there is just one target for a fishdrone esc, but it should be easy to add some more.

**Comment by conuthead** [comment]
Thanks brycedjohnson, I would like to help out however I can. I do have fully functional and flying code for stm32f051.. however its a ugly mess to look at. Who can maybe add me to the slack group?

**Comment by YanikTheYak** [comment]
@conuthead very interested to see your code. Even if it’s a mess. Is it in C or assembler? Is it in GitHub?
I have wraith32 that I’ve been dabbling with using the code here. 
I was thinking of porting blheli, but this seems to not be the direction for the project. So interested to see your take on it.

**Comment by brycedjohnson** [comment]
If you'd like to get added shoot me an email at bryce@redpinelabs.com and I'll forward it to someone that can add you.  Unfortunately the slack chat rolls its history after enough chatting, so it may looks blank on that channel right now, but shoot out questions and let me know if you need help getting what we have to build.

**Comment by conuthead** [comment]
@YanikTheYak.  Its all in C using the HAL drivers. Its a completely ground up version,  I did this because, i wanted to play with some new commutation and pwm techniques. I started a new "issue" with a link to the rcgroups thread with the hardware and some videos of my progress and first flight. I just finished getting proshot working properly ( *&%%& bit shifting) and dshot commands today. The problem is the code is not cleaned up, and its embarrassing poorly written. I only wrote it because I made an ESC that i had no firmware for. I knew the logic to drive it ( and have some slightly different methods) but wrote expecting nobody to ever see it.  I will do my best to clean it up and post it on my rcgroups blog in the next couple days ( have to get 2 more boards built too before i can fly with all 4).

cheers bryce, I don't know if I can help much but I would like to learn.

**Comment by mikeller** [comment]
@conuthead: What's your email? I can send you an invite to slack.

**Comment by conuthead** [comment]
alkazorithmedia@gmail.com .. TY.

**Comment by YanikTheYak** [comment]
@conuthead sounds very cool. Look forward to seeing it.

**Comment by rogersba** [comment]
I've been trying to workout the hardware for ESC's, is there a thread to determining the sizing? If so, I would love to know because I'm new to hardware and would love to learn how you guys figured out your component values. I want to build my own soon using the STSPIN32F0

**Comment by conuthead** [comment]
@rogersba 
We don't really have a hardware thread going. If you are interested in a specific hardware maybe start a thread on rcgroups. There's a diy electronics forum on there. I started playing with the stspin32f0 chips but have been sidetracked by the stm32f051. The limitation is the adc speed of the stspin32f0 might not be sufficient for high rpm motors and there is no comparator on board.

**Comment by jaxxzer** [comment]
@mikeller Please add me to the slack channel jwalser90@gmail.com, I would like to contribute.

**Comment by mikeller** [comment]
@jaxxzer: You can register for Slack yourself at https://slack.betaflight.com/.

**Comment by jaxxzer** [comment]
> I do have fully functional and flying code for stm32f051

@conuthead can I take a look at any of that code? ugly is ok.

**Comment by conuthead** [comment]
Hi, It's all here.
https://github.com/conuthead/f051bldc
It's a work in progress still.

**Comment by jaxxzer** [comment]
I've heard recently from @conuthead that he has successfully configured the op amps in the STSPIN to work as the comparators.
