### ISSUE TITLE
I have a Wraith32 setup for development

### ISSUE THREAD

**Issue by YanikTheYak** [betaflight/betaflight-esc#34]
Hi, I’m looking to contribute. 
I code, C, C++ and assembler. Have some experience of BLHELI_S
I have a wraith ESC setup on stlinkv2.
Have built, flashed it, and got the debugger working. 
Made a small mod to make the LED flash, just to check all was well. 

Looking to work on migrating some BLHeli assembler to C.
What areas are people not working on, so I can be most helpful?

I was thinking of getting flashing working through 4 way? Or has this been done?

Also have a question about the best way to add a new profile, since wraiths LEDs don’t seem to map quite right. If someone can give an example of a second ESC profile in the make files/config files, that would really help me. 

Regards
Ian

**Comment by DieHertz** [comment]
We would like to move away from the blheli interfaces and either use dshot or serial Passthrough like KISS

**Comment by YanikTheYak** [comment]
Hi
So the plan is to use dshot to flash the ESCs from the flight controller? I’m guessing through Betaflight?
So we’d be dropping blheli-configurator?

Does a protocol exist already to perform flashing? Or would we be creating some new commands to extend the dshot protocol?

I will read up on dshot :)

Ian

**Comment by DieHertz** [comment]
Blheli Configurator is my project, we won't be dropping anything

**Comment by jaxxzer** [comment]
I've made a target file for the wraith32: https://github.com/betaflight/betaflight-esc/pull/39
