### ISSUE TITLE
Easy dev hardware

### ISSUE THREAD

**Issue by conuthead** [betaflight/betaflight-esc#35]
I just noticed this project a day or two ago. After I had finished writing my own firmware. I wish I had found this first, would have saved some time.  Oh well. Anyway i have some wraith32 pin compatible boards that I am using for testing. They are two layer boards so you can use any cheap 5 dollar pcb printing house to make it. I have some bare boards extra if anyone wants one. The pins broken out with pin headers are for swd, clk, pa2, a uart rxtx, a boot0

https://www.rcgroups.com/forums/showthread.php?3048660-Writing-ESC-firmware-and-a-32-bit-speed-conroller-using-STM32f051-and-MP6531

**Comment by jaxxzer** [comment]
Interested, do you have any extra hardware you can send? Please contact me at jwalser90@gmail.com

Also interested in talking about your code.
